// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package firewall

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-unifi/sdk/go/unifi/internal"
)

type ZonePolicyOrder struct {
	pulumi.CustomResourceState

	// Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
	AfterPredefinedIds pulumi.StringArrayOutput `pulumi:"afterPredefinedIds"`
	// Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
	BeforePredefinedIds pulumi.StringArrayOutput `pulumi:"beforePredefinedIds"`
	// ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
	DestinationZoneId pulumi.StringOutput `pulumi:"destinationZoneId"`
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site pulumi.StringOutput `pulumi:"site"`
	// ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
	SourceZoneId pulumi.StringOutput `pulumi:"sourceZoneId"`
}

// NewZonePolicyOrder registers a new resource with the given unique name, arguments, and options.
func NewZonePolicyOrder(ctx *pulumi.Context,
	name string, args *ZonePolicyOrderArgs, opts ...pulumi.ResourceOption) (*ZonePolicyOrder, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DestinationZoneId == nil {
		return nil, errors.New("invalid value for required argument 'DestinationZoneId'")
	}
	if args.SourceZoneId == nil {
		return nil, errors.New("invalid value for required argument 'SourceZoneId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ZonePolicyOrder
	err := ctx.RegisterResource("unifi:firewall/zonePolicyOrder:ZonePolicyOrder", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetZonePolicyOrder gets an existing ZonePolicyOrder resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetZonePolicyOrder(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ZonePolicyOrderState, opts ...pulumi.ResourceOption) (*ZonePolicyOrder, error) {
	var resource ZonePolicyOrder
	err := ctx.ReadResource("unifi:firewall/zonePolicyOrder:ZonePolicyOrder", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ZonePolicyOrder resources.
type zonePolicyOrderState struct {
	// Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
	AfterPredefinedIds []string `pulumi:"afterPredefinedIds"`
	// Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
	BeforePredefinedIds []string `pulumi:"beforePredefinedIds"`
	// ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
	DestinationZoneId *string `pulumi:"destinationZoneId"`
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site *string `pulumi:"site"`
	// ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
	SourceZoneId *string `pulumi:"sourceZoneId"`
}

type ZonePolicyOrderState struct {
	// Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
	AfterPredefinedIds pulumi.StringArrayInput
	// Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
	BeforePredefinedIds pulumi.StringArrayInput
	// ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
	DestinationZoneId pulumi.StringPtrInput
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site pulumi.StringPtrInput
	// ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
	SourceZoneId pulumi.StringPtrInput
}

func (ZonePolicyOrderState) ElementType() reflect.Type {
	return reflect.TypeOf((*zonePolicyOrderState)(nil)).Elem()
}

type zonePolicyOrderArgs struct {
	// Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
	AfterPredefinedIds []string `pulumi:"afterPredefinedIds"`
	// Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
	BeforePredefinedIds []string `pulumi:"beforePredefinedIds"`
	// ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
	DestinationZoneId string `pulumi:"destinationZoneId"`
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site *string `pulumi:"site"`
	// ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
	SourceZoneId string `pulumi:"sourceZoneId"`
}

// The set of arguments for constructing a ZonePolicyOrder resource.
type ZonePolicyOrderArgs struct {
	// Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
	AfterPredefinedIds pulumi.StringArrayInput
	// Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
	BeforePredefinedIds pulumi.StringArrayInput
	// ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
	DestinationZoneId pulumi.StringInput
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site pulumi.StringPtrInput
	// ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
	SourceZoneId pulumi.StringInput
}

func (ZonePolicyOrderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*zonePolicyOrderArgs)(nil)).Elem()
}

type ZonePolicyOrderInput interface {
	pulumi.Input

	ToZonePolicyOrderOutput() ZonePolicyOrderOutput
	ToZonePolicyOrderOutputWithContext(ctx context.Context) ZonePolicyOrderOutput
}

func (*ZonePolicyOrder) ElementType() reflect.Type {
	return reflect.TypeOf((**ZonePolicyOrder)(nil)).Elem()
}

func (i *ZonePolicyOrder) ToZonePolicyOrderOutput() ZonePolicyOrderOutput {
	return i.ToZonePolicyOrderOutputWithContext(context.Background())
}

func (i *ZonePolicyOrder) ToZonePolicyOrderOutputWithContext(ctx context.Context) ZonePolicyOrderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ZonePolicyOrderOutput)
}

// ZonePolicyOrderArrayInput is an input type that accepts ZonePolicyOrderArray and ZonePolicyOrderArrayOutput values.
// You can construct a concrete instance of `ZonePolicyOrderArrayInput` via:
//
//	ZonePolicyOrderArray{ ZonePolicyOrderArgs{...} }
type ZonePolicyOrderArrayInput interface {
	pulumi.Input

	ToZonePolicyOrderArrayOutput() ZonePolicyOrderArrayOutput
	ToZonePolicyOrderArrayOutputWithContext(context.Context) ZonePolicyOrderArrayOutput
}

type ZonePolicyOrderArray []ZonePolicyOrderInput

func (ZonePolicyOrderArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ZonePolicyOrder)(nil)).Elem()
}

func (i ZonePolicyOrderArray) ToZonePolicyOrderArrayOutput() ZonePolicyOrderArrayOutput {
	return i.ToZonePolicyOrderArrayOutputWithContext(context.Background())
}

func (i ZonePolicyOrderArray) ToZonePolicyOrderArrayOutputWithContext(ctx context.Context) ZonePolicyOrderArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ZonePolicyOrderArrayOutput)
}

// ZonePolicyOrderMapInput is an input type that accepts ZonePolicyOrderMap and ZonePolicyOrderMapOutput values.
// You can construct a concrete instance of `ZonePolicyOrderMapInput` via:
//
//	ZonePolicyOrderMap{ "key": ZonePolicyOrderArgs{...} }
type ZonePolicyOrderMapInput interface {
	pulumi.Input

	ToZonePolicyOrderMapOutput() ZonePolicyOrderMapOutput
	ToZonePolicyOrderMapOutputWithContext(context.Context) ZonePolicyOrderMapOutput
}

type ZonePolicyOrderMap map[string]ZonePolicyOrderInput

func (ZonePolicyOrderMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ZonePolicyOrder)(nil)).Elem()
}

func (i ZonePolicyOrderMap) ToZonePolicyOrderMapOutput() ZonePolicyOrderMapOutput {
	return i.ToZonePolicyOrderMapOutputWithContext(context.Background())
}

func (i ZonePolicyOrderMap) ToZonePolicyOrderMapOutputWithContext(ctx context.Context) ZonePolicyOrderMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ZonePolicyOrderMapOutput)
}

type ZonePolicyOrderOutput struct{ *pulumi.OutputState }

func (ZonePolicyOrderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ZonePolicyOrder)(nil)).Elem()
}

func (o ZonePolicyOrderOutput) ToZonePolicyOrderOutput() ZonePolicyOrderOutput {
	return o
}

func (o ZonePolicyOrderOutput) ToZonePolicyOrderOutputWithContext(ctx context.Context) ZonePolicyOrderOutput {
	return o
}

// Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
func (o ZonePolicyOrderOutput) AfterPredefinedIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ZonePolicyOrder) pulumi.StringArrayOutput { return v.AfterPredefinedIds }).(pulumi.StringArrayOutput)
}

// Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
func (o ZonePolicyOrderOutput) BeforePredefinedIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ZonePolicyOrder) pulumi.StringArrayOutput { return v.BeforePredefinedIds }).(pulumi.StringArrayOutput)
}

// ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
func (o ZonePolicyOrderOutput) DestinationZoneId() pulumi.StringOutput {
	return o.ApplyT(func(v *ZonePolicyOrder) pulumi.StringOutput { return v.DestinationZoneId }).(pulumi.StringOutput)
}

// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
func (o ZonePolicyOrderOutput) Site() pulumi.StringOutput {
	return o.ApplyT(func(v *ZonePolicyOrder) pulumi.StringOutput { return v.Site }).(pulumi.StringOutput)
}

// ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
func (o ZonePolicyOrderOutput) SourceZoneId() pulumi.StringOutput {
	return o.ApplyT(func(v *ZonePolicyOrder) pulumi.StringOutput { return v.SourceZoneId }).(pulumi.StringOutput)
}

type ZonePolicyOrderArrayOutput struct{ *pulumi.OutputState }

func (ZonePolicyOrderArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ZonePolicyOrder)(nil)).Elem()
}

func (o ZonePolicyOrderArrayOutput) ToZonePolicyOrderArrayOutput() ZonePolicyOrderArrayOutput {
	return o
}

func (o ZonePolicyOrderArrayOutput) ToZonePolicyOrderArrayOutputWithContext(ctx context.Context) ZonePolicyOrderArrayOutput {
	return o
}

func (o ZonePolicyOrderArrayOutput) Index(i pulumi.IntInput) ZonePolicyOrderOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ZonePolicyOrder {
		return vs[0].([]*ZonePolicyOrder)[vs[1].(int)]
	}).(ZonePolicyOrderOutput)
}

type ZonePolicyOrderMapOutput struct{ *pulumi.OutputState }

func (ZonePolicyOrderMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ZonePolicyOrder)(nil)).Elem()
}

func (o ZonePolicyOrderMapOutput) ToZonePolicyOrderMapOutput() ZonePolicyOrderMapOutput {
	return o
}

func (o ZonePolicyOrderMapOutput) ToZonePolicyOrderMapOutputWithContext(ctx context.Context) ZonePolicyOrderMapOutput {
	return o
}

func (o ZonePolicyOrderMapOutput) MapIndex(k pulumi.StringInput) ZonePolicyOrderOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ZonePolicyOrder {
		return vs[0].(map[string]*ZonePolicyOrder)[vs[1].(string)]
	}).(ZonePolicyOrderOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ZonePolicyOrderInput)(nil)).Elem(), &ZonePolicyOrder{})
	pulumi.RegisterInputType(reflect.TypeOf((*ZonePolicyOrderArrayInput)(nil)).Elem(), ZonePolicyOrderArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ZonePolicyOrderMapInput)(nil)).Elem(), ZonePolicyOrderMap{})
	pulumi.RegisterOutputType(ZonePolicyOrderOutput{})
	pulumi.RegisterOutputType(ZonePolicyOrderArrayOutput{})
	pulumi.RegisterOutputType(ZonePolicyOrderMapOutput{})
}
