// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package firewall

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-unifi/sdk/go/unifi/internal"
)

type ZonePolicy struct {
	pulumi.CustomResourceState

	// Determines which action to take on matching traffic. Must be one of `BLOCK`, `ALLOW`, or `REJECT`.
	Action pulumi.StringOutput `pulumi:"action"`
	// Creates a built-in policy for the opposite Zone Pair to automatically allow the return traffic. If disabled, return traffic must be manually allowed
	AutoAllowReturnTraffic pulumi.BoolOutput `pulumi:"autoAllowReturnTraffic"`
	// Optionally match on a firewall connection state such as traffic associated with an already existing connection. Valid values are `ALL`, `RESPOND_ONLY`, or `CUSTOM`.
	ConnectionStateType pulumi.StringOutput `pulumi:"connectionStateType"`
	// Connection states to match when `connectionStateType` is `CUSTOM`. Valid values include `ESTABLISHED`, `NEW`, `RELATED`, and `INVALID`.
	ConnectionStates pulumi.StringArrayOutput `pulumi:"connectionStates"`
	// Description of the firewall zone policy.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The zone matching the destination of the traffic. Optionally match on a specific destination inside the zone.
	Destination ZonePolicyDestinationOutput `pulumi:"destination"`
	// Enable the policy
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Priority index for the policy. This value is assigned by the UniFi controller and cannot be set directly. To control policy ordering, use the `firewall.ZonePolicyOrder` resource (planned for future release).
	Index pulumi.IntOutput `pulumi:"index"`
	// Optionally match on only IPv4 or IPv6. Valid values are `BOTH`, `IPV4`, or `IPV6`.
	IpVersion pulumi.StringOutput `pulumi:"ipVersion"`
	// Enable to generate syslog entries when traffic is matched.
	Logging pulumi.BoolOutput `pulumi:"logging"`
	// Optionally match on traffic encrypted by IPsec. This is typically used for Ipsec Policy-Based VPNs. Valid values are `MATCH_IP_SEC` or `MATCH_NON_IP_SEC`.
	MatchIpSecType pulumi.StringPtrOutput `pulumi:"matchIpSecType"`
	// Whether to match the opposite protocol.
	MatchOppositeProtocol pulumi.BoolOutput `pulumi:"matchOppositeProtocol"`
	// The name of the firewall zone policy.
	Name pulumi.StringOutput `pulumi:"name"`
	// Optionally match a specific protocol. Valid values include: `all`, `tcpUdp`, `tcp`, `udp`, etc.
	Protocol pulumi.StringOutput `pulumi:"protocol"`
	// Enforce this policy at specific times.
	Schedule ZonePolicyScheduleOutput `pulumi:"schedule"`
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site pulumi.StringOutput `pulumi:"site"`
	// The zone matching the source of the traffic. Optionally match on a specific source inside the zone.
	Source ZonePolicySourceOutput `pulumi:"source"`
}

// NewZonePolicy registers a new resource with the given unique name, arguments, and options.
func NewZonePolicy(ctx *pulumi.Context,
	name string, args *ZonePolicyArgs, opts ...pulumi.ResourceOption) (*ZonePolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Action == nil {
		return nil, errors.New("invalid value for required argument 'Action'")
	}
	if args.Destination == nil {
		return nil, errors.New("invalid value for required argument 'Destination'")
	}
	if args.Source == nil {
		return nil, errors.New("invalid value for required argument 'Source'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ZonePolicy
	err := ctx.RegisterResource("unifi:firewall/zonePolicy:ZonePolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetZonePolicy gets an existing ZonePolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetZonePolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ZonePolicyState, opts ...pulumi.ResourceOption) (*ZonePolicy, error) {
	var resource ZonePolicy
	err := ctx.ReadResource("unifi:firewall/zonePolicy:ZonePolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ZonePolicy resources.
type zonePolicyState struct {
	// Determines which action to take on matching traffic. Must be one of `BLOCK`, `ALLOW`, or `REJECT`.
	Action *string `pulumi:"action"`
	// Creates a built-in policy for the opposite Zone Pair to automatically allow the return traffic. If disabled, return traffic must be manually allowed
	AutoAllowReturnTraffic *bool `pulumi:"autoAllowReturnTraffic"`
	// Optionally match on a firewall connection state such as traffic associated with an already existing connection. Valid values are `ALL`, `RESPOND_ONLY`, or `CUSTOM`.
	ConnectionStateType *string `pulumi:"connectionStateType"`
	// Connection states to match when `connectionStateType` is `CUSTOM`. Valid values include `ESTABLISHED`, `NEW`, `RELATED`, and `INVALID`.
	ConnectionStates []string `pulumi:"connectionStates"`
	// Description of the firewall zone policy.
	Description *string `pulumi:"description"`
	// The zone matching the destination of the traffic. Optionally match on a specific destination inside the zone.
	Destination *ZonePolicyDestination `pulumi:"destination"`
	// Enable the policy
	Enabled *bool `pulumi:"enabled"`
	// Priority index for the policy. This value is assigned by the UniFi controller and cannot be set directly. To control policy ordering, use the `firewall.ZonePolicyOrder` resource (planned for future release).
	Index *int `pulumi:"index"`
	// Optionally match on only IPv4 or IPv6. Valid values are `BOTH`, `IPV4`, or `IPV6`.
	IpVersion *string `pulumi:"ipVersion"`
	// Enable to generate syslog entries when traffic is matched.
	Logging *bool `pulumi:"logging"`
	// Optionally match on traffic encrypted by IPsec. This is typically used for Ipsec Policy-Based VPNs. Valid values are `MATCH_IP_SEC` or `MATCH_NON_IP_SEC`.
	MatchIpSecType *string `pulumi:"matchIpSecType"`
	// Whether to match the opposite protocol.
	MatchOppositeProtocol *bool `pulumi:"matchOppositeProtocol"`
	// The name of the firewall zone policy.
	Name *string `pulumi:"name"`
	// Optionally match a specific protocol. Valid values include: `all`, `tcpUdp`, `tcp`, `udp`, etc.
	Protocol *string `pulumi:"protocol"`
	// Enforce this policy at specific times.
	Schedule *ZonePolicySchedule `pulumi:"schedule"`
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site *string `pulumi:"site"`
	// The zone matching the source of the traffic. Optionally match on a specific source inside the zone.
	Source *ZonePolicySource `pulumi:"source"`
}

type ZonePolicyState struct {
	// Determines which action to take on matching traffic. Must be one of `BLOCK`, `ALLOW`, or `REJECT`.
	Action pulumi.StringPtrInput
	// Creates a built-in policy for the opposite Zone Pair to automatically allow the return traffic. If disabled, return traffic must be manually allowed
	AutoAllowReturnTraffic pulumi.BoolPtrInput
	// Optionally match on a firewall connection state such as traffic associated with an already existing connection. Valid values are `ALL`, `RESPOND_ONLY`, or `CUSTOM`.
	ConnectionStateType pulumi.StringPtrInput
	// Connection states to match when `connectionStateType` is `CUSTOM`. Valid values include `ESTABLISHED`, `NEW`, `RELATED`, and `INVALID`.
	ConnectionStates pulumi.StringArrayInput
	// Description of the firewall zone policy.
	Description pulumi.StringPtrInput
	// The zone matching the destination of the traffic. Optionally match on a specific destination inside the zone.
	Destination ZonePolicyDestinationPtrInput
	// Enable the policy
	Enabled pulumi.BoolPtrInput
	// Priority index for the policy. This value is assigned by the UniFi controller and cannot be set directly. To control policy ordering, use the `firewall.ZonePolicyOrder` resource (planned for future release).
	Index pulumi.IntPtrInput
	// Optionally match on only IPv4 or IPv6. Valid values are `BOTH`, `IPV4`, or `IPV6`.
	IpVersion pulumi.StringPtrInput
	// Enable to generate syslog entries when traffic is matched.
	Logging pulumi.BoolPtrInput
	// Optionally match on traffic encrypted by IPsec. This is typically used for Ipsec Policy-Based VPNs. Valid values are `MATCH_IP_SEC` or `MATCH_NON_IP_SEC`.
	MatchIpSecType pulumi.StringPtrInput
	// Whether to match the opposite protocol.
	MatchOppositeProtocol pulumi.BoolPtrInput
	// The name of the firewall zone policy.
	Name pulumi.StringPtrInput
	// Optionally match a specific protocol. Valid values include: `all`, `tcpUdp`, `tcp`, `udp`, etc.
	Protocol pulumi.StringPtrInput
	// Enforce this policy at specific times.
	Schedule ZonePolicySchedulePtrInput
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site pulumi.StringPtrInput
	// The zone matching the source of the traffic. Optionally match on a specific source inside the zone.
	Source ZonePolicySourcePtrInput
}

func (ZonePolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*zonePolicyState)(nil)).Elem()
}

type zonePolicyArgs struct {
	// Determines which action to take on matching traffic. Must be one of `BLOCK`, `ALLOW`, or `REJECT`.
	Action string `pulumi:"action"`
	// Creates a built-in policy for the opposite Zone Pair to automatically allow the return traffic. If disabled, return traffic must be manually allowed
	AutoAllowReturnTraffic *bool `pulumi:"autoAllowReturnTraffic"`
	// Optionally match on a firewall connection state such as traffic associated with an already existing connection. Valid values are `ALL`, `RESPOND_ONLY`, or `CUSTOM`.
	ConnectionStateType *string `pulumi:"connectionStateType"`
	// Connection states to match when `connectionStateType` is `CUSTOM`. Valid values include `ESTABLISHED`, `NEW`, `RELATED`, and `INVALID`.
	ConnectionStates []string `pulumi:"connectionStates"`
	// Description of the firewall zone policy.
	Description *string `pulumi:"description"`
	// The zone matching the destination of the traffic. Optionally match on a specific destination inside the zone.
	Destination ZonePolicyDestination `pulumi:"destination"`
	// Enable the policy
	Enabled *bool `pulumi:"enabled"`
	// Optionally match on only IPv4 or IPv6. Valid values are `BOTH`, `IPV4`, or `IPV6`.
	IpVersion *string `pulumi:"ipVersion"`
	// Enable to generate syslog entries when traffic is matched.
	Logging *bool `pulumi:"logging"`
	// Optionally match on traffic encrypted by IPsec. This is typically used for Ipsec Policy-Based VPNs. Valid values are `MATCH_IP_SEC` or `MATCH_NON_IP_SEC`.
	MatchIpSecType *string `pulumi:"matchIpSecType"`
	// Whether to match the opposite protocol.
	MatchOppositeProtocol *bool `pulumi:"matchOppositeProtocol"`
	// The name of the firewall zone policy.
	Name *string `pulumi:"name"`
	// Optionally match a specific protocol. Valid values include: `all`, `tcpUdp`, `tcp`, `udp`, etc.
	Protocol *string `pulumi:"protocol"`
	// Enforce this policy at specific times.
	Schedule *ZonePolicySchedule `pulumi:"schedule"`
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site *string `pulumi:"site"`
	// The zone matching the source of the traffic. Optionally match on a specific source inside the zone.
	Source ZonePolicySource `pulumi:"source"`
}

// The set of arguments for constructing a ZonePolicy resource.
type ZonePolicyArgs struct {
	// Determines which action to take on matching traffic. Must be one of `BLOCK`, `ALLOW`, or `REJECT`.
	Action pulumi.StringInput
	// Creates a built-in policy for the opposite Zone Pair to automatically allow the return traffic. If disabled, return traffic must be manually allowed
	AutoAllowReturnTraffic pulumi.BoolPtrInput
	// Optionally match on a firewall connection state such as traffic associated with an already existing connection. Valid values are `ALL`, `RESPOND_ONLY`, or `CUSTOM`.
	ConnectionStateType pulumi.StringPtrInput
	// Connection states to match when `connectionStateType` is `CUSTOM`. Valid values include `ESTABLISHED`, `NEW`, `RELATED`, and `INVALID`.
	ConnectionStates pulumi.StringArrayInput
	// Description of the firewall zone policy.
	Description pulumi.StringPtrInput
	// The zone matching the destination of the traffic. Optionally match on a specific destination inside the zone.
	Destination ZonePolicyDestinationInput
	// Enable the policy
	Enabled pulumi.BoolPtrInput
	// Optionally match on only IPv4 or IPv6. Valid values are `BOTH`, `IPV4`, or `IPV6`.
	IpVersion pulumi.StringPtrInput
	// Enable to generate syslog entries when traffic is matched.
	Logging pulumi.BoolPtrInput
	// Optionally match on traffic encrypted by IPsec. This is typically used for Ipsec Policy-Based VPNs. Valid values are `MATCH_IP_SEC` or `MATCH_NON_IP_SEC`.
	MatchIpSecType pulumi.StringPtrInput
	// Whether to match the opposite protocol.
	MatchOppositeProtocol pulumi.BoolPtrInput
	// The name of the firewall zone policy.
	Name pulumi.StringPtrInput
	// Optionally match a specific protocol. Valid values include: `all`, `tcpUdp`, `tcp`, `udp`, etc.
	Protocol pulumi.StringPtrInput
	// Enforce this policy at specific times.
	Schedule ZonePolicySchedulePtrInput
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site pulumi.StringPtrInput
	// The zone matching the source of the traffic. Optionally match on a specific source inside the zone.
	Source ZonePolicySourceInput
}

func (ZonePolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*zonePolicyArgs)(nil)).Elem()
}

type ZonePolicyInput interface {
	pulumi.Input

	ToZonePolicyOutput() ZonePolicyOutput
	ToZonePolicyOutputWithContext(ctx context.Context) ZonePolicyOutput
}

func (*ZonePolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**ZonePolicy)(nil)).Elem()
}

func (i *ZonePolicy) ToZonePolicyOutput() ZonePolicyOutput {
	return i.ToZonePolicyOutputWithContext(context.Background())
}

func (i *ZonePolicy) ToZonePolicyOutputWithContext(ctx context.Context) ZonePolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ZonePolicyOutput)
}

// ZonePolicyArrayInput is an input type that accepts ZonePolicyArray and ZonePolicyArrayOutput values.
// You can construct a concrete instance of `ZonePolicyArrayInput` via:
//
//	ZonePolicyArray{ ZonePolicyArgs{...} }
type ZonePolicyArrayInput interface {
	pulumi.Input

	ToZonePolicyArrayOutput() ZonePolicyArrayOutput
	ToZonePolicyArrayOutputWithContext(context.Context) ZonePolicyArrayOutput
}

type ZonePolicyArray []ZonePolicyInput

func (ZonePolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ZonePolicy)(nil)).Elem()
}

func (i ZonePolicyArray) ToZonePolicyArrayOutput() ZonePolicyArrayOutput {
	return i.ToZonePolicyArrayOutputWithContext(context.Background())
}

func (i ZonePolicyArray) ToZonePolicyArrayOutputWithContext(ctx context.Context) ZonePolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ZonePolicyArrayOutput)
}

// ZonePolicyMapInput is an input type that accepts ZonePolicyMap and ZonePolicyMapOutput values.
// You can construct a concrete instance of `ZonePolicyMapInput` via:
//
//	ZonePolicyMap{ "key": ZonePolicyArgs{...} }
type ZonePolicyMapInput interface {
	pulumi.Input

	ToZonePolicyMapOutput() ZonePolicyMapOutput
	ToZonePolicyMapOutputWithContext(context.Context) ZonePolicyMapOutput
}

type ZonePolicyMap map[string]ZonePolicyInput

func (ZonePolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ZonePolicy)(nil)).Elem()
}

func (i ZonePolicyMap) ToZonePolicyMapOutput() ZonePolicyMapOutput {
	return i.ToZonePolicyMapOutputWithContext(context.Background())
}

func (i ZonePolicyMap) ToZonePolicyMapOutputWithContext(ctx context.Context) ZonePolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ZonePolicyMapOutput)
}

type ZonePolicyOutput struct{ *pulumi.OutputState }

func (ZonePolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ZonePolicy)(nil)).Elem()
}

func (o ZonePolicyOutput) ToZonePolicyOutput() ZonePolicyOutput {
	return o
}

func (o ZonePolicyOutput) ToZonePolicyOutputWithContext(ctx context.Context) ZonePolicyOutput {
	return o
}

// Determines which action to take on matching traffic. Must be one of `BLOCK`, `ALLOW`, or `REJECT`.
func (o ZonePolicyOutput) Action() pulumi.StringOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.StringOutput { return v.Action }).(pulumi.StringOutput)
}

// Creates a built-in policy for the opposite Zone Pair to automatically allow the return traffic. If disabled, return traffic must be manually allowed
func (o ZonePolicyOutput) AutoAllowReturnTraffic() pulumi.BoolOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.BoolOutput { return v.AutoAllowReturnTraffic }).(pulumi.BoolOutput)
}

// Optionally match on a firewall connection state such as traffic associated with an already existing connection. Valid values are `ALL`, `RESPOND_ONLY`, or `CUSTOM`.
func (o ZonePolicyOutput) ConnectionStateType() pulumi.StringOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.StringOutput { return v.ConnectionStateType }).(pulumi.StringOutput)
}

// Connection states to match when `connectionStateType` is `CUSTOM`. Valid values include `ESTABLISHED`, `NEW`, `RELATED`, and `INVALID`.
func (o ZonePolicyOutput) ConnectionStates() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.StringArrayOutput { return v.ConnectionStates }).(pulumi.StringArrayOutput)
}

// Description of the firewall zone policy.
func (o ZonePolicyOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The zone matching the destination of the traffic. Optionally match on a specific destination inside the zone.
func (o ZonePolicyOutput) Destination() ZonePolicyDestinationOutput {
	return o.ApplyT(func(v *ZonePolicy) ZonePolicyDestinationOutput { return v.Destination }).(ZonePolicyDestinationOutput)
}

// Enable the policy
func (o ZonePolicyOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Priority index for the policy. This value is assigned by the UniFi controller and cannot be set directly. To control policy ordering, use the `firewall.ZonePolicyOrder` resource (planned for future release).
func (o ZonePolicyOutput) Index() pulumi.IntOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.IntOutput { return v.Index }).(pulumi.IntOutput)
}

// Optionally match on only IPv4 or IPv6. Valid values are `BOTH`, `IPV4`, or `IPV6`.
func (o ZonePolicyOutput) IpVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.StringOutput { return v.IpVersion }).(pulumi.StringOutput)
}

// Enable to generate syslog entries when traffic is matched.
func (o ZonePolicyOutput) Logging() pulumi.BoolOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.BoolOutput { return v.Logging }).(pulumi.BoolOutput)
}

// Optionally match on traffic encrypted by IPsec. This is typically used for Ipsec Policy-Based VPNs. Valid values are `MATCH_IP_SEC` or `MATCH_NON_IP_SEC`.
func (o ZonePolicyOutput) MatchIpSecType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.StringPtrOutput { return v.MatchIpSecType }).(pulumi.StringPtrOutput)
}

// Whether to match the opposite protocol.
func (o ZonePolicyOutput) MatchOppositeProtocol() pulumi.BoolOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.BoolOutput { return v.MatchOppositeProtocol }).(pulumi.BoolOutput)
}

// The name of the firewall zone policy.
func (o ZonePolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Optionally match a specific protocol. Valid values include: `all`, `tcpUdp`, `tcp`, `udp`, etc.
func (o ZonePolicyOutput) Protocol() pulumi.StringOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.StringOutput { return v.Protocol }).(pulumi.StringOutput)
}

// Enforce this policy at specific times.
func (o ZonePolicyOutput) Schedule() ZonePolicyScheduleOutput {
	return o.ApplyT(func(v *ZonePolicy) ZonePolicyScheduleOutput { return v.Schedule }).(ZonePolicyScheduleOutput)
}

// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
func (o ZonePolicyOutput) Site() pulumi.StringOutput {
	return o.ApplyT(func(v *ZonePolicy) pulumi.StringOutput { return v.Site }).(pulumi.StringOutput)
}

// The zone matching the source of the traffic. Optionally match on a specific source inside the zone.
func (o ZonePolicyOutput) Source() ZonePolicySourceOutput {
	return o.ApplyT(func(v *ZonePolicy) ZonePolicySourceOutput { return v.Source }).(ZonePolicySourceOutput)
}

type ZonePolicyArrayOutput struct{ *pulumi.OutputState }

func (ZonePolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ZonePolicy)(nil)).Elem()
}

func (o ZonePolicyArrayOutput) ToZonePolicyArrayOutput() ZonePolicyArrayOutput {
	return o
}

func (o ZonePolicyArrayOutput) ToZonePolicyArrayOutputWithContext(ctx context.Context) ZonePolicyArrayOutput {
	return o
}

func (o ZonePolicyArrayOutput) Index(i pulumi.IntInput) ZonePolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ZonePolicy {
		return vs[0].([]*ZonePolicy)[vs[1].(int)]
	}).(ZonePolicyOutput)
}

type ZonePolicyMapOutput struct{ *pulumi.OutputState }

func (ZonePolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ZonePolicy)(nil)).Elem()
}

func (o ZonePolicyMapOutput) ToZonePolicyMapOutput() ZonePolicyMapOutput {
	return o
}

func (o ZonePolicyMapOutput) ToZonePolicyMapOutputWithContext(ctx context.Context) ZonePolicyMapOutput {
	return o
}

func (o ZonePolicyMapOutput) MapIndex(k pulumi.StringInput) ZonePolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ZonePolicy {
		return vs[0].(map[string]*ZonePolicy)[vs[1].(string)]
	}).(ZonePolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ZonePolicyInput)(nil)).Elem(), &ZonePolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*ZonePolicyArrayInput)(nil)).Elem(), ZonePolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ZonePolicyMapInput)(nil)).Elem(), ZonePolicyMap{})
	pulumi.RegisterOutputType(ZonePolicyOutput{})
	pulumi.RegisterOutputType(ZonePolicyArrayOutput{})
	pulumi.RegisterOutputType(ZonePolicyMapOutput{})
}
