// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package iam

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-unifi/sdk/go/unifi/internal"
)

func LookupUser(ctx *pulumi.Context, args *LookupUserArgs, opts ...pulumi.InvokeOption) (*LookupUserResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupUserResult
	err := ctx.Invoke("unifi:iam/getUser:getUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getUser.
type LookupUserArgs struct {
	Mac  string  `pulumi:"mac"`
	Site *string `pulumi:"site"`
}

// A collection of values returned by getUser.
type LookupUserResult struct {
	Blocked        bool   `pulumi:"blocked"`
	DevIdOverride  int    `pulumi:"devIdOverride"`
	FixedIp        string `pulumi:"fixedIp"`
	Hostname       string `pulumi:"hostname"`
	Id             string `pulumi:"id"`
	Ip             string `pulumi:"ip"`
	LocalDnsRecord string `pulumi:"localDnsRecord"`
	Mac            string `pulumi:"mac"`
	Name           string `pulumi:"name"`
	NetworkId      string `pulumi:"networkId"`
	Note           string `pulumi:"note"`
	Site           string `pulumi:"site"`
	UserGroupId    string `pulumi:"userGroupId"`
}

func LookupUserOutput(ctx *pulumi.Context, args LookupUserOutputArgs, opts ...pulumi.InvokeOption) LookupUserResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupUserResultOutput, error) {
			args := v.(LookupUserArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("unifi:iam/getUser:getUser", args, LookupUserResultOutput{}, options).(LookupUserResultOutput), nil
		}).(LookupUserResultOutput)
}

// A collection of arguments for invoking getUser.
type LookupUserOutputArgs struct {
	Mac  pulumi.StringInput    `pulumi:"mac"`
	Site pulumi.StringPtrInput `pulumi:"site"`
}

func (LookupUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserArgs)(nil)).Elem()
}

// A collection of values returned by getUser.
type LookupUserResultOutput struct{ *pulumi.OutputState }

func (LookupUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserResult)(nil)).Elem()
}

func (o LookupUserResultOutput) ToLookupUserResultOutput() LookupUserResultOutput {
	return o
}

func (o LookupUserResultOutput) ToLookupUserResultOutputWithContext(ctx context.Context) LookupUserResultOutput {
	return o
}

func (o LookupUserResultOutput) Blocked() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupUserResult) bool { return v.Blocked }).(pulumi.BoolOutput)
}

func (o LookupUserResultOutput) DevIdOverride() pulumi.IntOutput {
	return o.ApplyT(func(v LookupUserResult) int { return v.DevIdOverride }).(pulumi.IntOutput)
}

func (o LookupUserResultOutput) FixedIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.FixedIp }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Hostname }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Ip }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) LocalDnsRecord() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.LocalDnsRecord }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) Mac() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Mac }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.NetworkId }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) Note() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Note }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) Site() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Site }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) UserGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.UserGroupId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupUserResultOutput{})
}
