# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['ZonePolicyOrderArgs', 'ZonePolicyOrder']

@pulumi.input_type
class ZonePolicyOrderArgs:
    def __init__(__self__, *,
                 destination_zone_id: pulumi.Input[_builtins.str],
                 source_zone_id: pulumi.Input[_builtins.str],
                 after_predefined_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 before_predefined_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 site: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a ZonePolicyOrder resource.
        :param pulumi.Input[_builtins.str] destination_zone_id: ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        :param pulumi.Input[_builtins.str] source_zone_id: ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] after_predefined_ids: Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] before_predefined_ids: Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        pulumi.set(__self__, "destination_zone_id", destination_zone_id)
        pulumi.set(__self__, "source_zone_id", source_zone_id)
        if after_predefined_ids is not None:
            pulumi.set(__self__, "after_predefined_ids", after_predefined_ids)
        if before_predefined_ids is not None:
            pulumi.set(__self__, "before_predefined_ids", before_predefined_ids)
        if site is not None:
            pulumi.set(__self__, "site", site)

    @_builtins.property
    @pulumi.getter(name="destinationZoneId")
    def destination_zone_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        """
        return pulumi.get(self, "destination_zone_id")

    @destination_zone_id.setter
    def destination_zone_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "destination_zone_id", value)

    @_builtins.property
    @pulumi.getter(name="sourceZoneId")
    def source_zone_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        """
        return pulumi.get(self, "source_zone_id")

    @source_zone_id.setter
    def source_zone_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "source_zone_id", value)

    @_builtins.property
    @pulumi.getter(name="afterPredefinedIds")
    def after_predefined_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        """
        return pulumi.get(self, "after_predefined_ids")

    @after_predefined_ids.setter
    def after_predefined_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "after_predefined_ids", value)

    @_builtins.property
    @pulumi.getter(name="beforePredefinedIds")
    def before_predefined_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        """
        return pulumi.get(self, "before_predefined_ids")

    @before_predefined_ids.setter
    def before_predefined_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "before_predefined_ids", value)

    @_builtins.property
    @pulumi.getter
    def site(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @site.setter
    def site(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "site", value)


@pulumi.input_type
class _ZonePolicyOrderState:
    def __init__(__self__, *,
                 after_predefined_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 before_predefined_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 destination_zone_id: Optional[pulumi.Input[_builtins.str]] = None,
                 site: Optional[pulumi.Input[_builtins.str]] = None,
                 source_zone_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ZonePolicyOrder resources.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] after_predefined_ids: Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] before_predefined_ids: Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        :param pulumi.Input[_builtins.str] destination_zone_id: ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        :param pulumi.Input[_builtins.str] source_zone_id: ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        """
        if after_predefined_ids is not None:
            pulumi.set(__self__, "after_predefined_ids", after_predefined_ids)
        if before_predefined_ids is not None:
            pulumi.set(__self__, "before_predefined_ids", before_predefined_ids)
        if destination_zone_id is not None:
            pulumi.set(__self__, "destination_zone_id", destination_zone_id)
        if site is not None:
            pulumi.set(__self__, "site", site)
        if source_zone_id is not None:
            pulumi.set(__self__, "source_zone_id", source_zone_id)

    @_builtins.property
    @pulumi.getter(name="afterPredefinedIds")
    def after_predefined_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        """
        return pulumi.get(self, "after_predefined_ids")

    @after_predefined_ids.setter
    def after_predefined_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "after_predefined_ids", value)

    @_builtins.property
    @pulumi.getter(name="beforePredefinedIds")
    def before_predefined_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        """
        return pulumi.get(self, "before_predefined_ids")

    @before_predefined_ids.setter
    def before_predefined_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "before_predefined_ids", value)

    @_builtins.property
    @pulumi.getter(name="destinationZoneId")
    def destination_zone_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        """
        return pulumi.get(self, "destination_zone_id")

    @destination_zone_id.setter
    def destination_zone_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "destination_zone_id", value)

    @_builtins.property
    @pulumi.getter
    def site(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @site.setter
    def site(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "site", value)

    @_builtins.property
    @pulumi.getter(name="sourceZoneId")
    def source_zone_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        """
        return pulumi.get(self, "source_zone_id")

    @source_zone_id.setter
    def source_zone_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "source_zone_id", value)


@pulumi.type_token("unifi:firewall/zonePolicyOrder:ZonePolicyOrder")
class ZonePolicyOrder(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 after_predefined_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 before_predefined_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 destination_zone_id: Optional[pulumi.Input[_builtins.str]] = None,
                 site: Optional[pulumi.Input[_builtins.str]] = None,
                 source_zone_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a ZonePolicyOrder resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] after_predefined_ids: Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] before_predefined_ids: Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        :param pulumi.Input[_builtins.str] destination_zone_id: ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        :param pulumi.Input[_builtins.str] source_zone_id: ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ZonePolicyOrderArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ZonePolicyOrder resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ZonePolicyOrderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ZonePolicyOrderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 after_predefined_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 before_predefined_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 destination_zone_id: Optional[pulumi.Input[_builtins.str]] = None,
                 site: Optional[pulumi.Input[_builtins.str]] = None,
                 source_zone_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ZonePolicyOrderArgs.__new__(ZonePolicyOrderArgs)

            __props__.__dict__["after_predefined_ids"] = after_predefined_ids
            __props__.__dict__["before_predefined_ids"] = before_predefined_ids
            if destination_zone_id is None and not opts.urn:
                raise TypeError("Missing required property 'destination_zone_id'")
            __props__.__dict__["destination_zone_id"] = destination_zone_id
            __props__.__dict__["site"] = site
            if source_zone_id is None and not opts.urn:
                raise TypeError("Missing required property 'source_zone_id'")
            __props__.__dict__["source_zone_id"] = source_zone_id
        super(ZonePolicyOrder, __self__).__init__(
            'unifi:firewall/zonePolicyOrder:ZonePolicyOrder',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            after_predefined_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            before_predefined_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            destination_zone_id: Optional[pulumi.Input[_builtins.str]] = None,
            site: Optional[pulumi.Input[_builtins.str]] = None,
            source_zone_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'ZonePolicyOrder':
        """
        Get an existing ZonePolicyOrder resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] after_predefined_ids: Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] before_predefined_ids: Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        :param pulumi.Input[_builtins.str] destination_zone_id: ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        :param pulumi.Input[_builtins.str] source_zone_id: ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ZonePolicyOrderState.__new__(_ZonePolicyOrderState)

        __props__.__dict__["after_predefined_ids"] = after_predefined_ids
        __props__.__dict__["before_predefined_ids"] = before_predefined_ids
        __props__.__dict__["destination_zone_id"] = destination_zone_id
        __props__.__dict__["site"] = site
        __props__.__dict__["source_zone_id"] = source_zone_id
        return ZonePolicyOrder(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="afterPredefinedIds")
    def after_predefined_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Ordered IDs of custom `firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        """
        return pulumi.get(self, "after_predefined_ids")

    @_builtins.property
    @pulumi.getter(name="beforePredefinedIds")
    def before_predefined_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Ordered IDs of custom `firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
        """
        return pulumi.get(self, "before_predefined_ids")

    @_builtins.property
    @pulumi.getter(name="destinationZoneId")
    def destination_zone_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        """
        return pulumi.get(self, "destination_zone_id")

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @_builtins.property
    @pulumi.getter(name="sourceZoneId")
    def source_zone_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
        """
        return pulumi.get(self, "source_zone_id")

