// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getRecord(args?: GetRecordArgs, opts?: pulumi.InvokeOptions): Promise<GetRecordResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("unifi:dns/getRecord:getRecord", {
        "name": args.name,
        "site": args.site,
        "value": args.value,
    }, opts);
}

/**
 * A collection of arguments for invoking getRecord.
 */
export interface GetRecordArgs {
    name?: string;
    site?: string;
    value?: string;
}

/**
 * A collection of values returned by getRecord.
 */
export interface GetRecordResult {
    readonly enabled: boolean;
    readonly id: string;
    readonly name: string;
    readonly port: number;
    readonly priority: number;
    readonly site: string;
    readonly ttl: number;
    readonly type: string;
    readonly value: string;
    readonly weight: number;
}
export function getRecordOutput(args?: GetRecordOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRecordResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("unifi:dns/getRecord:getRecord", {
        "name": args.name,
        "site": args.site,
        "value": args.value,
    }, opts);
}

/**
 * A collection of arguments for invoking getRecord.
 */
export interface GetRecordOutputArgs {
    name?: pulumi.Input<string | undefined>;
    site?: pulumi.Input<string | undefined>;
    value?: pulumi.Input<string | undefined>;
}
