// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unifi

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-unifi/sdk/go/unifi/internal"
)

// Deprecated: unifi.index/getapgroup.getApGroup has been deprecated in favor of unifi.ap/getgroup.getGroup
func LookupApGroup(ctx *pulumi.Context, args *LookupApGroupArgs, opts ...pulumi.InvokeOption) (*LookupApGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupApGroupResult
	err := ctx.Invoke("unifi:index/getApGroup:getApGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApGroup.
type LookupApGroupArgs struct {
	Name *string `pulumi:"name"`
	Site *string `pulumi:"site"`
}

// A collection of values returned by getApGroup.
type LookupApGroupResult struct {
	Id   string  `pulumi:"id"`
	Name *string `pulumi:"name"`
	Site string  `pulumi:"site"`
}

func LookupApGroupOutput(ctx *pulumi.Context, args LookupApGroupOutputArgs, opts ...pulumi.InvokeOption) LookupApGroupResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupApGroupResultOutput, error) {
			args := v.(LookupApGroupArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("unifi:index/getApGroup:getApGroup", args, LookupApGroupResultOutput{}, options).(LookupApGroupResultOutput), nil
		}).(LookupApGroupResultOutput)
}

// A collection of arguments for invoking getApGroup.
type LookupApGroupOutputArgs struct {
	Name pulumi.StringPtrInput `pulumi:"name"`
	Site pulumi.StringPtrInput `pulumi:"site"`
}

func (LookupApGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApGroupArgs)(nil)).Elem()
}

// A collection of values returned by getApGroup.
type LookupApGroupResultOutput struct{ *pulumi.OutputState }

func (LookupApGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApGroupResult)(nil)).Elem()
}

func (o LookupApGroupResultOutput) ToLookupApGroupResultOutput() LookupApGroupResultOutput {
	return o
}

func (o LookupApGroupResultOutput) ToLookupApGroupResultOutputWithContext(ctx context.Context) LookupApGroupResultOutput {
	return o
}

func (o LookupApGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupApGroupResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupApGroupResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o LookupApGroupResultOutput) Site() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApGroupResult) string { return v.Site }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupApGroupResultOutput{})
}
