// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unifi

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-unifi/sdk/go/unifi/internal"
)

func LookupAccount(ctx *pulumi.Context, args *LookupAccountArgs, opts ...pulumi.InvokeOption) (*LookupAccountResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAccountResult
	err := ctx.Invoke("unifi:index/getAccount:getAccount", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAccount.
type LookupAccountArgs struct {
	Name string  `pulumi:"name"`
	Site *string `pulumi:"site"`
}

// A collection of values returned by getAccount.
type LookupAccountResult struct {
	Id               string `pulumi:"id"`
	Name             string `pulumi:"name"`
	NetworkId        string `pulumi:"networkId"`
	Password         string `pulumi:"password"`
	Site             string `pulumi:"site"`
	TunnelMediumType int    `pulumi:"tunnelMediumType"`
	TunnelType       int    `pulumi:"tunnelType"`
	Vlan             int    `pulumi:"vlan"`
}

func LookupAccountOutput(ctx *pulumi.Context, args LookupAccountOutputArgs, opts ...pulumi.InvokeOption) LookupAccountResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupAccountResultOutput, error) {
			args := v.(LookupAccountArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("unifi:index/getAccount:getAccount", args, LookupAccountResultOutput{}, options).(LookupAccountResultOutput), nil
		}).(LookupAccountResultOutput)
}

// A collection of arguments for invoking getAccount.
type LookupAccountOutputArgs struct {
	Name pulumi.StringInput    `pulumi:"name"`
	Site pulumi.StringPtrInput `pulumi:"site"`
}

func (LookupAccountOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAccountArgs)(nil)).Elem()
}

// A collection of values returned by getAccount.
type LookupAccountResultOutput struct{ *pulumi.OutputState }

func (LookupAccountResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAccountResult)(nil)).Elem()
}

func (o LookupAccountResultOutput) ToLookupAccountResultOutput() LookupAccountResultOutput {
	return o
}

func (o LookupAccountResultOutput) ToLookupAccountResultOutputWithContext(ctx context.Context) LookupAccountResultOutput {
	return o
}

func (o LookupAccountResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupAccountResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupAccountResultOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.NetworkId }).(pulumi.StringOutput)
}

func (o LookupAccountResultOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.Password }).(pulumi.StringOutput)
}

func (o LookupAccountResultOutput) Site() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.Site }).(pulumi.StringOutput)
}

func (o LookupAccountResultOutput) TunnelMediumType() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAccountResult) int { return v.TunnelMediumType }).(pulumi.IntOutput)
}

func (o LookupAccountResultOutput) TunnelType() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAccountResult) int { return v.TunnelType }).(pulumi.IntOutput)
}

func (o LookupAccountResultOutput) Vlan() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAccountResult) int { return v.Vlan }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAccountResultOutput{})
}
