// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unifi

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-unifi/sdk/go/unifi/internal"
)

func LookupNetwork(ctx *pulumi.Context, args *LookupNetworkArgs, opts ...pulumi.InvokeOption) (*LookupNetworkResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNetworkResult
	err := ctx.Invoke("unifi:index/getNetwork:getNetwork", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetwork.
type LookupNetworkArgs struct {
	Id   *string `pulumi:"id"`
	Name *string `pulumi:"name"`
	Site *string `pulumi:"site"`
}

// A collection of values returned by getNetwork.
type LookupNetworkResult struct {
	DhcpDns                 []string `pulumi:"dhcpDns"`
	DhcpEnabled             bool     `pulumi:"dhcpEnabled"`
	DhcpGuarding            bool     `pulumi:"dhcpGuarding"`
	DhcpLease               int      `pulumi:"dhcpLease"`
	DhcpStart               string   `pulumi:"dhcpStart"`
	DhcpStop                string   `pulumi:"dhcpStop"`
	DhcpV6Dns               []string `pulumi:"dhcpV6Dns"`
	DhcpV6DnsAuto           bool     `pulumi:"dhcpV6DnsAuto"`
	DhcpV6Enabled           bool     `pulumi:"dhcpV6Enabled"`
	DhcpV6Lease             int      `pulumi:"dhcpV6Lease"`
	DhcpV6Start             string   `pulumi:"dhcpV6Start"`
	DhcpV6Stop              string   `pulumi:"dhcpV6Stop"`
	DhcpdBootEnabled        bool     `pulumi:"dhcpdBootEnabled"`
	DhcpdBootFilename       string   `pulumi:"dhcpdBootFilename"`
	DhcpdBootServer         string   `pulumi:"dhcpdBootServer"`
	DhcpdGateway            string   `pulumi:"dhcpdGateway"`
	DhcpdGatewayEnabled     bool     `pulumi:"dhcpdGatewayEnabled"`
	DomainName              string   `pulumi:"domainName"`
	FirewallZoneId          string   `pulumi:"firewallZoneId"`
	Id                      string   `pulumi:"id"`
	IgmpSnooping            bool     `pulumi:"igmpSnooping"`
	Ipv6InterfaceType       string   `pulumi:"ipv6InterfaceType"`
	Ipv6PdInterface         string   `pulumi:"ipv6PdInterface"`
	Ipv6PdPrefixid          string   `pulumi:"ipv6PdPrefixid"`
	Ipv6PdStart             string   `pulumi:"ipv6PdStart"`
	Ipv6PdStop              string   `pulumi:"ipv6PdStop"`
	Ipv6RaEnable            bool     `pulumi:"ipv6RaEnable"`
	Ipv6RaPreferredLifetime int      `pulumi:"ipv6RaPreferredLifetime"`
	Ipv6RaPriority          string   `pulumi:"ipv6RaPriority"`
	Ipv6RaValidLifetime     int      `pulumi:"ipv6RaValidLifetime"`
	Ipv6StaticSubnet        string   `pulumi:"ipv6StaticSubnet"`
	MulticastDns            bool     `pulumi:"multicastDns"`
	Name                    string   `pulumi:"name"`
	NetworkGroup            string   `pulumi:"networkGroup"`
	Purpose                 string   `pulumi:"purpose"`
	Site                    string   `pulumi:"site"`
	Subnet                  string   `pulumi:"subnet"`
	VlanId                  int      `pulumi:"vlanId"`
	WanDhcpV6PdSize         int      `pulumi:"wanDhcpV6PdSize"`
	WanDns                  []string `pulumi:"wanDns"`
	WanEgressQos            int      `pulumi:"wanEgressQos"`
	WanGateway              string   `pulumi:"wanGateway"`
	WanGatewayV6            string   `pulumi:"wanGatewayV6"`
	WanIp                   string   `pulumi:"wanIp"`
	WanIpv6                 string   `pulumi:"wanIpv6"`
	WanNetmask              string   `pulumi:"wanNetmask"`
	WanNetworkgroup         string   `pulumi:"wanNetworkgroup"`
	WanPrefixlen            int      `pulumi:"wanPrefixlen"`
	WanType                 string   `pulumi:"wanType"`
	WanTypeV6               string   `pulumi:"wanTypeV6"`
	WanUsername             string   `pulumi:"wanUsername"`
	XWanPassword            string   `pulumi:"xWanPassword"`
}

func LookupNetworkOutput(ctx *pulumi.Context, args LookupNetworkOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNetworkResultOutput, error) {
			args := v.(LookupNetworkArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("unifi:index/getNetwork:getNetwork", args, LookupNetworkResultOutput{}, options).(LookupNetworkResultOutput), nil
		}).(LookupNetworkResultOutput)
}

// A collection of arguments for invoking getNetwork.
type LookupNetworkOutputArgs struct {
	Id   pulumi.StringPtrInput `pulumi:"id"`
	Name pulumi.StringPtrInput `pulumi:"name"`
	Site pulumi.StringPtrInput `pulumi:"site"`
}

func (LookupNetworkOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkArgs)(nil)).Elem()
}

// A collection of values returned by getNetwork.
type LookupNetworkResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkResult)(nil)).Elem()
}

func (o LookupNetworkResultOutput) ToLookupNetworkResultOutput() LookupNetworkResultOutput {
	return o
}

func (o LookupNetworkResultOutput) ToLookupNetworkResultOutputWithContext(ctx context.Context) LookupNetworkResultOutput {
	return o
}

func (o LookupNetworkResultOutput) DhcpDns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNetworkResult) []string { return v.DhcpDns }).(pulumi.StringArrayOutput)
}

func (o LookupNetworkResultOutput) DhcpEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkResult) bool { return v.DhcpEnabled }).(pulumi.BoolOutput)
}

func (o LookupNetworkResultOutput) DhcpGuarding() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkResult) bool { return v.DhcpGuarding }).(pulumi.BoolOutput)
}

func (o LookupNetworkResultOutput) DhcpLease() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkResult) int { return v.DhcpLease }).(pulumi.IntOutput)
}

func (o LookupNetworkResultOutput) DhcpStart() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.DhcpStart }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) DhcpStop() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.DhcpStop }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) DhcpV6Dns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNetworkResult) []string { return v.DhcpV6Dns }).(pulumi.StringArrayOutput)
}

func (o LookupNetworkResultOutput) DhcpV6DnsAuto() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkResult) bool { return v.DhcpV6DnsAuto }).(pulumi.BoolOutput)
}

func (o LookupNetworkResultOutput) DhcpV6Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkResult) bool { return v.DhcpV6Enabled }).(pulumi.BoolOutput)
}

func (o LookupNetworkResultOutput) DhcpV6Lease() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkResult) int { return v.DhcpV6Lease }).(pulumi.IntOutput)
}

func (o LookupNetworkResultOutput) DhcpV6Start() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.DhcpV6Start }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) DhcpV6Stop() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.DhcpV6Stop }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) DhcpdBootEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkResult) bool { return v.DhcpdBootEnabled }).(pulumi.BoolOutput)
}

func (o LookupNetworkResultOutput) DhcpdBootFilename() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.DhcpdBootFilename }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) DhcpdBootServer() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.DhcpdBootServer }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) DhcpdGateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.DhcpdGateway }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) DhcpdGatewayEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkResult) bool { return v.DhcpdGatewayEnabled }).(pulumi.BoolOutput)
}

func (o LookupNetworkResultOutput) DomainName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.DomainName }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) FirewallZoneId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.FirewallZoneId }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) IgmpSnooping() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkResult) bool { return v.IgmpSnooping }).(pulumi.BoolOutput)
}

func (o LookupNetworkResultOutput) Ipv6InterfaceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Ipv6InterfaceType }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Ipv6PdInterface() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Ipv6PdInterface }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Ipv6PdPrefixid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Ipv6PdPrefixid }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Ipv6PdStart() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Ipv6PdStart }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Ipv6PdStop() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Ipv6PdStop }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Ipv6RaEnable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkResult) bool { return v.Ipv6RaEnable }).(pulumi.BoolOutput)
}

func (o LookupNetworkResultOutput) Ipv6RaPreferredLifetime() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkResult) int { return v.Ipv6RaPreferredLifetime }).(pulumi.IntOutput)
}

func (o LookupNetworkResultOutput) Ipv6RaPriority() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Ipv6RaPriority }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Ipv6RaValidLifetime() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkResult) int { return v.Ipv6RaValidLifetime }).(pulumi.IntOutput)
}

func (o LookupNetworkResultOutput) Ipv6StaticSubnet() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Ipv6StaticSubnet }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) MulticastDns() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkResult) bool { return v.MulticastDns }).(pulumi.BoolOutput)
}

func (o LookupNetworkResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) NetworkGroup() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.NetworkGroup }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Purpose() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Purpose }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Site() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Site }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Subnet() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Subnet }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) VlanId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkResult) int { return v.VlanId }).(pulumi.IntOutput)
}

func (o LookupNetworkResultOutput) WanDhcpV6PdSize() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkResult) int { return v.WanDhcpV6PdSize }).(pulumi.IntOutput)
}

func (o LookupNetworkResultOutput) WanDns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNetworkResult) []string { return v.WanDns }).(pulumi.StringArrayOutput)
}

func (o LookupNetworkResultOutput) WanEgressQos() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkResult) int { return v.WanEgressQos }).(pulumi.IntOutput)
}

func (o LookupNetworkResultOutput) WanGateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.WanGateway }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) WanGatewayV6() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.WanGatewayV6 }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) WanIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.WanIp }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) WanIpv6() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.WanIpv6 }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) WanNetmask() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.WanNetmask }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) WanNetworkgroup() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.WanNetworkgroup }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) WanPrefixlen() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkResult) int { return v.WanPrefixlen }).(pulumi.IntOutput)
}

func (o LookupNetworkResultOutput) WanType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.WanType }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) WanTypeV6() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.WanTypeV6 }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) WanUsername() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.WanUsername }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) XWanPassword() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.XWanPassword }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkResultOutput{})
}
