// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package setting

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-unifi/sdk/go/unifi/internal"
)

type GlobalSwitch struct {
	pulumi.CustomResourceState

	// Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `globalSwitch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
	AclDeviceIsolations pulumi.StringArrayOutput `pulumi:"aclDeviceIsolations"`
	// Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
	AclL3Isolations GlobalSwitchAclL3IsolationArrayOutput `pulumi:"aclL3Isolations"`
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site pulumi.StringOutput `pulumi:"site"`
	// Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
	SwitchExclusions pulumi.StringArrayOutput `pulumi:"switchExclusions"`
}

// NewGlobalSwitch registers a new resource with the given unique name, arguments, and options.
func NewGlobalSwitch(ctx *pulumi.Context,
	name string, args *GlobalSwitchArgs, opts ...pulumi.ResourceOption) (*GlobalSwitch, error) {
	if args == nil {
		args = &GlobalSwitchArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GlobalSwitch
	err := ctx.RegisterResource("unifi:setting/globalSwitch:GlobalSwitch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGlobalSwitch gets an existing GlobalSwitch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGlobalSwitch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GlobalSwitchState, opts ...pulumi.ResourceOption) (*GlobalSwitch, error) {
	var resource GlobalSwitch
	err := ctx.ReadResource("unifi:setting/globalSwitch:GlobalSwitch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GlobalSwitch resources.
type globalSwitchState struct {
	// Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `globalSwitch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
	AclDeviceIsolations []string `pulumi:"aclDeviceIsolations"`
	// Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
	AclL3Isolations []GlobalSwitchAclL3Isolation `pulumi:"aclL3Isolations"`
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site *string `pulumi:"site"`
	// Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
	SwitchExclusions []string `pulumi:"switchExclusions"`
}

type GlobalSwitchState struct {
	// Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `globalSwitch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
	AclDeviceIsolations pulumi.StringArrayInput
	// Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
	AclL3Isolations GlobalSwitchAclL3IsolationArrayInput
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site pulumi.StringPtrInput
	// Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
	SwitchExclusions pulumi.StringArrayInput
}

func (GlobalSwitchState) ElementType() reflect.Type {
	return reflect.TypeOf((*globalSwitchState)(nil)).Elem()
}

type globalSwitchArgs struct {
	// Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `globalSwitch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
	AclDeviceIsolations []string `pulumi:"aclDeviceIsolations"`
	// Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
	AclL3Isolations []GlobalSwitchAclL3Isolation `pulumi:"aclL3Isolations"`
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site *string `pulumi:"site"`
	// Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
	SwitchExclusions []string `pulumi:"switchExclusions"`
}

// The set of arguments for constructing a GlobalSwitch resource.
type GlobalSwitchArgs struct {
	// Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `globalSwitch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
	AclDeviceIsolations pulumi.StringArrayInput
	// Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
	AclL3Isolations GlobalSwitchAclL3IsolationArrayInput
	// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
	Site pulumi.StringPtrInput
	// Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
	SwitchExclusions pulumi.StringArrayInput
}

func (GlobalSwitchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*globalSwitchArgs)(nil)).Elem()
}

type GlobalSwitchInput interface {
	pulumi.Input

	ToGlobalSwitchOutput() GlobalSwitchOutput
	ToGlobalSwitchOutputWithContext(ctx context.Context) GlobalSwitchOutput
}

func (*GlobalSwitch) ElementType() reflect.Type {
	return reflect.TypeOf((**GlobalSwitch)(nil)).Elem()
}

func (i *GlobalSwitch) ToGlobalSwitchOutput() GlobalSwitchOutput {
	return i.ToGlobalSwitchOutputWithContext(context.Background())
}

func (i *GlobalSwitch) ToGlobalSwitchOutputWithContext(ctx context.Context) GlobalSwitchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GlobalSwitchOutput)
}

// GlobalSwitchArrayInput is an input type that accepts GlobalSwitchArray and GlobalSwitchArrayOutput values.
// You can construct a concrete instance of `GlobalSwitchArrayInput` via:
//
//	GlobalSwitchArray{ GlobalSwitchArgs{...} }
type GlobalSwitchArrayInput interface {
	pulumi.Input

	ToGlobalSwitchArrayOutput() GlobalSwitchArrayOutput
	ToGlobalSwitchArrayOutputWithContext(context.Context) GlobalSwitchArrayOutput
}

type GlobalSwitchArray []GlobalSwitchInput

func (GlobalSwitchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GlobalSwitch)(nil)).Elem()
}

func (i GlobalSwitchArray) ToGlobalSwitchArrayOutput() GlobalSwitchArrayOutput {
	return i.ToGlobalSwitchArrayOutputWithContext(context.Background())
}

func (i GlobalSwitchArray) ToGlobalSwitchArrayOutputWithContext(ctx context.Context) GlobalSwitchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GlobalSwitchArrayOutput)
}

// GlobalSwitchMapInput is an input type that accepts GlobalSwitchMap and GlobalSwitchMapOutput values.
// You can construct a concrete instance of `GlobalSwitchMapInput` via:
//
//	GlobalSwitchMap{ "key": GlobalSwitchArgs{...} }
type GlobalSwitchMapInput interface {
	pulumi.Input

	ToGlobalSwitchMapOutput() GlobalSwitchMapOutput
	ToGlobalSwitchMapOutputWithContext(context.Context) GlobalSwitchMapOutput
}

type GlobalSwitchMap map[string]GlobalSwitchInput

func (GlobalSwitchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GlobalSwitch)(nil)).Elem()
}

func (i GlobalSwitchMap) ToGlobalSwitchMapOutput() GlobalSwitchMapOutput {
	return i.ToGlobalSwitchMapOutputWithContext(context.Background())
}

func (i GlobalSwitchMap) ToGlobalSwitchMapOutputWithContext(ctx context.Context) GlobalSwitchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GlobalSwitchMapOutput)
}

type GlobalSwitchOutput struct{ *pulumi.OutputState }

func (GlobalSwitchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GlobalSwitch)(nil)).Elem()
}

func (o GlobalSwitchOutput) ToGlobalSwitchOutput() GlobalSwitchOutput {
	return o
}

func (o GlobalSwitchOutput) ToGlobalSwitchOutputWithContext(ctx context.Context) GlobalSwitchOutput {
	return o
}

// Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `globalSwitch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
func (o GlobalSwitchOutput) AclDeviceIsolations() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GlobalSwitch) pulumi.StringArrayOutput { return v.AclDeviceIsolations }).(pulumi.StringArrayOutput)
}

// Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
func (o GlobalSwitchOutput) AclL3Isolations() GlobalSwitchAclL3IsolationArrayOutput {
	return o.ApplyT(func(v *GlobalSwitch) GlobalSwitchAclL3IsolationArrayOutput { return v.AclL3Isolations }).(GlobalSwitchAclL3IsolationArrayOutput)
}

// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
func (o GlobalSwitchOutput) Site() pulumi.StringOutput {
	return o.ApplyT(func(v *GlobalSwitch) pulumi.StringOutput { return v.Site }).(pulumi.StringOutput)
}

// Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
func (o GlobalSwitchOutput) SwitchExclusions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GlobalSwitch) pulumi.StringArrayOutput { return v.SwitchExclusions }).(pulumi.StringArrayOutput)
}

type GlobalSwitchArrayOutput struct{ *pulumi.OutputState }

func (GlobalSwitchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GlobalSwitch)(nil)).Elem()
}

func (o GlobalSwitchArrayOutput) ToGlobalSwitchArrayOutput() GlobalSwitchArrayOutput {
	return o
}

func (o GlobalSwitchArrayOutput) ToGlobalSwitchArrayOutputWithContext(ctx context.Context) GlobalSwitchArrayOutput {
	return o
}

func (o GlobalSwitchArrayOutput) Index(i pulumi.IntInput) GlobalSwitchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GlobalSwitch {
		return vs[0].([]*GlobalSwitch)[vs[1].(int)]
	}).(GlobalSwitchOutput)
}

type GlobalSwitchMapOutput struct{ *pulumi.OutputState }

func (GlobalSwitchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GlobalSwitch)(nil)).Elem()
}

func (o GlobalSwitchMapOutput) ToGlobalSwitchMapOutput() GlobalSwitchMapOutput {
	return o
}

func (o GlobalSwitchMapOutput) ToGlobalSwitchMapOutputWithContext(ctx context.Context) GlobalSwitchMapOutput {
	return o
}

func (o GlobalSwitchMapOutput) MapIndex(k pulumi.StringInput) GlobalSwitchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GlobalSwitch {
		return vs[0].(map[string]*GlobalSwitch)[vs[1].(string)]
	}).(GlobalSwitchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GlobalSwitchInput)(nil)).Elem(), &GlobalSwitch{})
	pulumi.RegisterInputType(reflect.TypeOf((*GlobalSwitchArrayInput)(nil)).Elem(), GlobalSwitchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GlobalSwitchMapInput)(nil)).Elem(), GlobalSwitchMap{})
	pulumi.RegisterOutputType(GlobalSwitchOutput{})
	pulumi.RegisterOutputType(GlobalSwitchArrayOutput{})
	pulumi.RegisterOutputType(GlobalSwitchMapOutput{})
}
