# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._inputs import *

__all__ = ['GlobalSwitchArgs', 'GlobalSwitch']

@pulumi.input_type
class GlobalSwitchArgs:
    def __init__(__self__, *,
                 acl_device_isolations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 acl_l3_isolations: Optional[pulumi.Input[Sequence[pulumi.Input['GlobalSwitchAclL3IsolationArgs']]]] = None,
                 site: Optional[pulumi.Input[_builtins.str]] = None,
                 switch_exclusions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a GlobalSwitch resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] acl_device_isolations: Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `global_switch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        :param pulumi.Input[Sequence[pulumi.Input['GlobalSwitchAclL3IsolationArgs']]] acl_l3_isolations: Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] switch_exclusions: Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        """
        if acl_device_isolations is not None:
            pulumi.set(__self__, "acl_device_isolations", acl_device_isolations)
        if acl_l3_isolations is not None:
            pulumi.set(__self__, "acl_l3_isolations", acl_l3_isolations)
        if site is not None:
            pulumi.set(__self__, "site", site)
        if switch_exclusions is not None:
            pulumi.set(__self__, "switch_exclusions", switch_exclusions)

    @_builtins.property
    @pulumi.getter(name="aclDeviceIsolations")
    def acl_device_isolations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `global_switch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        """
        return pulumi.get(self, "acl_device_isolations")

    @acl_device_isolations.setter
    def acl_device_isolations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "acl_device_isolations", value)

    @_builtins.property
    @pulumi.getter(name="aclL3Isolations")
    def acl_l3_isolations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['GlobalSwitchAclL3IsolationArgs']]]]:
        """
        Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
        """
        return pulumi.get(self, "acl_l3_isolations")

    @acl_l3_isolations.setter
    def acl_l3_isolations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['GlobalSwitchAclL3IsolationArgs']]]]):
        pulumi.set(self, "acl_l3_isolations", value)

    @_builtins.property
    @pulumi.getter
    def site(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @site.setter
    def site(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "site", value)

    @_builtins.property
    @pulumi.getter(name="switchExclusions")
    def switch_exclusions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        """
        return pulumi.get(self, "switch_exclusions")

    @switch_exclusions.setter
    def switch_exclusions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "switch_exclusions", value)


@pulumi.input_type
class _GlobalSwitchState:
    def __init__(__self__, *,
                 acl_device_isolations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 acl_l3_isolations: Optional[pulumi.Input[Sequence[pulumi.Input['GlobalSwitchAclL3IsolationArgs']]]] = None,
                 site: Optional[pulumi.Input[_builtins.str]] = None,
                 switch_exclusions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering GlobalSwitch resources.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] acl_device_isolations: Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `global_switch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        :param pulumi.Input[Sequence[pulumi.Input['GlobalSwitchAclL3IsolationArgs']]] acl_l3_isolations: Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] switch_exclusions: Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        """
        if acl_device_isolations is not None:
            pulumi.set(__self__, "acl_device_isolations", acl_device_isolations)
        if acl_l3_isolations is not None:
            pulumi.set(__self__, "acl_l3_isolations", acl_l3_isolations)
        if site is not None:
            pulumi.set(__self__, "site", site)
        if switch_exclusions is not None:
            pulumi.set(__self__, "switch_exclusions", switch_exclusions)

    @_builtins.property
    @pulumi.getter(name="aclDeviceIsolations")
    def acl_device_isolations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `global_switch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        """
        return pulumi.get(self, "acl_device_isolations")

    @acl_device_isolations.setter
    def acl_device_isolations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "acl_device_isolations", value)

    @_builtins.property
    @pulumi.getter(name="aclL3Isolations")
    def acl_l3_isolations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['GlobalSwitchAclL3IsolationArgs']]]]:
        """
        Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
        """
        return pulumi.get(self, "acl_l3_isolations")

    @acl_l3_isolations.setter
    def acl_l3_isolations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['GlobalSwitchAclL3IsolationArgs']]]]):
        pulumi.set(self, "acl_l3_isolations", value)

    @_builtins.property
    @pulumi.getter
    def site(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @site.setter
    def site(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "site", value)

    @_builtins.property
    @pulumi.getter(name="switchExclusions")
    def switch_exclusions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        """
        return pulumi.get(self, "switch_exclusions")

    @switch_exclusions.setter
    def switch_exclusions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "switch_exclusions", value)


@pulumi.type_token("unifi:setting/globalSwitch:GlobalSwitch")
class GlobalSwitch(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 acl_device_isolations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 acl_l3_isolations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['GlobalSwitchAclL3IsolationArgs', 'GlobalSwitchAclL3IsolationArgsDict']]]]] = None,
                 site: Optional[pulumi.Input[_builtins.str]] = None,
                 switch_exclusions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Create a GlobalSwitch resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] acl_device_isolations: Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `global_switch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        :param pulumi.Input[Sequence[pulumi.Input[Union['GlobalSwitchAclL3IsolationArgs', 'GlobalSwitchAclL3IsolationArgsDict']]]] acl_l3_isolations: Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] switch_exclusions: Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[GlobalSwitchArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a GlobalSwitch resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param GlobalSwitchArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(GlobalSwitchArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 acl_device_isolations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 acl_l3_isolations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['GlobalSwitchAclL3IsolationArgs', 'GlobalSwitchAclL3IsolationArgsDict']]]]] = None,
                 site: Optional[pulumi.Input[_builtins.str]] = None,
                 switch_exclusions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = GlobalSwitchArgs.__new__(GlobalSwitchArgs)

            __props__.__dict__["acl_device_isolations"] = acl_device_isolations
            __props__.__dict__["acl_l3_isolations"] = acl_l3_isolations
            __props__.__dict__["site"] = site
            __props__.__dict__["switch_exclusions"] = switch_exclusions
        super(GlobalSwitch, __self__).__init__(
            'unifi:setting/globalSwitch:GlobalSwitch',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            acl_device_isolations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            acl_l3_isolations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['GlobalSwitchAclL3IsolationArgs', 'GlobalSwitchAclL3IsolationArgsDict']]]]] = None,
            site: Optional[pulumi.Input[_builtins.str]] = None,
            switch_exclusions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None) -> 'GlobalSwitch':
        """
        Get an existing GlobalSwitch resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] acl_device_isolations: Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `global_switch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        :param pulumi.Input[Sequence[pulumi.Input[Union['GlobalSwitchAclL3IsolationArgs', 'GlobalSwitchAclL3IsolationArgsDict']]]] acl_l3_isolations: Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] switch_exclusions: Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _GlobalSwitchState.__new__(_GlobalSwitchState)

        __props__.__dict__["acl_device_isolations"] = acl_device_isolations
        __props__.__dict__["acl_l3_isolations"] = acl_l3_isolations
        __props__.__dict__["site"] = site
        __props__.__dict__["switch_exclusions"] = switch_exclusions
        return GlobalSwitch(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="aclDeviceIsolations")
    def acl_device_isolations(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `global_switch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        """
        return pulumi.get(self, "acl_device_isolations")

    @_builtins.property
    @pulumi.getter(name="aclL3Isolations")
    def acl_l3_isolations(self) -> pulumi.Output[Sequence['outputs.GlobalSwitchAclL3Isolation']]:
        """
        Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
        """
        return pulumi.get(self, "acl_l3_isolations")

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @_builtins.property
    @pulumi.getter(name="switchExclusions")
    def switch_exclusions(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
        """
        return pulumi.get(self, "switch_exclusions")

