// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class GlobalSwitch extends pulumi.CustomResource {
    /**
     * Get an existing GlobalSwitch resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GlobalSwitchState, opts?: pulumi.CustomResourceOptions): GlobalSwitch {
        return new GlobalSwitch(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:setting/globalSwitch:GlobalSwitch';

    /**
     * Returns true if the given object is an instance of GlobalSwitch.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GlobalSwitch {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GlobalSwitch.__pulumiType;
    }

    /**
     * Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `globalSwitch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
     */
    declare public readonly aclDeviceIsolations: pulumi.Output<string[]>;
    /**
     * Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `unifi.Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
     */
    declare public readonly aclL3Isolations: pulumi.Output<outputs.setting.GlobalSwitchAclL3Isolation[]>;
    /**
     * The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
     */
    declare public readonly site: pulumi.Output<string>;
    /**
     * Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
     */
    declare public readonly switchExclusions: pulumi.Output<string[]>;

    /**
     * Create a GlobalSwitch resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: GlobalSwitchArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GlobalSwitchArgs | GlobalSwitchState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GlobalSwitchState | undefined;
            resourceInputs["aclDeviceIsolations"] = state?.aclDeviceIsolations;
            resourceInputs["aclL3Isolations"] = state?.aclL3Isolations;
            resourceInputs["site"] = state?.site;
            resourceInputs["switchExclusions"] = state?.switchExclusions;
        } else {
            const args = argsOrState as GlobalSwitchArgs | undefined;
            resourceInputs["aclDeviceIsolations"] = args?.aclDeviceIsolations;
            resourceInputs["aclL3Isolations"] = args?.aclL3Isolations;
            resourceInputs["site"] = args?.site;
            resourceInputs["switchExclusions"] = args?.switchExclusions;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GlobalSwitch.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GlobalSwitch resources.
 */
export interface GlobalSwitchState {
    /**
     * Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `globalSwitch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
     */
    aclDeviceIsolations?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `unifi.Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
     */
    aclL3Isolations?: pulumi.Input<pulumi.Input<inputs.setting.GlobalSwitchAclL3Isolation>[]>;
    /**
     * The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
     */
    site?: pulumi.Input<string>;
    /**
     * Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
     */
    switchExclusions?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a GlobalSwitch resource.
 */
export interface GlobalSwitchArgs {
    /**
     * Set of device identifiers to isolate (the controller's **Device Isolation** control). Each element is sent to the controller verbatim, with no validation or normalization: the UniFi `globalSwitch` API does not constrain this field's format, so supply the identifiers exactly as the controller expects them (refer to the controller UI). Reordering has no effect (this is an unordered set). At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
     */
    aclDeviceIsolations?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Set of layer-3 (network-to-network) isolation rules. Each entry isolates a source network from a set of destination networks. All values are UniFi network IDs (the `id` of a `unifi.Network` resource), not network names or CIDRs. Reordering has no effect (unordered set).
     */
    aclL3Isolations?: pulumi.Input<pulumi.Input<inputs.setting.GlobalSwitchAclL3Isolation>[]>;
    /**
     * The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
     */
    site?: pulumi.Input<string>;
    /**
     * Set of switch MAC addresses excluded from isolation enforcement. Each element must be the MAC address of a switch that is already adopted/managed by the controller; the controller rejects MACs that do not correspond to a known switch. MAC addresses are case-insensitive and may use `:` or `-` separators (e.g. `aa:bb:cc:dd:ee:ff` and `AA-BB-CC-DD-EE-FF` are treated as the same address and produce no diff); the value is kept as written. At least one element is required when set; the value cannot be cleared and is retained even if the attribute is later removed.
     */
    switchExclusions?: pulumi.Input<pulumi.Input<string>[]>;
}
