// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/** @deprecated unifi.index/getapgroup.getApGroup has been deprecated in favor of unifi.ap/getgroup.getGroup */
export function getApGroup(args?: GetApGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetApGroupResult> {
    pulumi.log.warn("getApGroup is deprecated: unifi.index/getapgroup.getApGroup has been deprecated in favor of unifi.ap/getgroup.getGroup")
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("unifi:index/getApGroup:getApGroup", {
        "name": args.name,
        "site": args.site,
    }, opts);
}

/**
 * A collection of arguments for invoking getApGroup.
 */
export interface GetApGroupArgs {
    name?: string;
    site?: string;
}

/**
 * A collection of values returned by getApGroup.
 */
export interface GetApGroupResult {
    readonly id: string;
    readonly name?: string;
    readonly site: string;
}
/** @deprecated unifi.index/getapgroup.getApGroup has been deprecated in favor of unifi.ap/getgroup.getGroup */
export function getApGroupOutput(args?: GetApGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetApGroupResult> {
    pulumi.log.warn("getApGroup is deprecated: unifi.index/getapgroup.getApGroup has been deprecated in favor of unifi.ap/getgroup.getGroup")
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("unifi:index/getApGroup:getApGroup", {
        "name": args.name,
        "site": args.site,
    }, opts);
}

/**
 * A collection of arguments for invoking getApGroup.
 */
export interface GetApGroupOutputArgs {
    name?: pulumi.Input<string>;
    site?: pulumi.Input<string>;
}
