// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class ZonePolicyOrder extends pulumi.CustomResource {
    /**
     * Get an existing ZonePolicyOrder resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ZonePolicyOrderState, opts?: pulumi.CustomResourceOptions): ZonePolicyOrder {
        return new ZonePolicyOrder(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:firewall/zonePolicyOrder:ZonePolicyOrder';

    /**
     * Returns true if the given object is an instance of ZonePolicyOrder.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ZonePolicyOrder {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ZonePolicyOrder.__pulumiType;
    }

    /**
     * Ordered IDs of custom `unifi.firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
     */
    declare public readonly afterPredefinedIds: pulumi.Output<string[] | undefined>;
    /**
     * Ordered IDs of custom `unifi.firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
     */
    declare public readonly beforePredefinedIds: pulumi.Output<string[] | undefined>;
    /**
     * ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
     */
    declare public readonly destinationZoneId: pulumi.Output<string>;
    /**
     * The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
     */
    declare public readonly site: pulumi.Output<string>;
    /**
     * ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
     */
    declare public readonly sourceZoneId: pulumi.Output<string>;

    /**
     * Create a ZonePolicyOrder resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ZonePolicyOrderArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ZonePolicyOrderArgs | ZonePolicyOrderState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ZonePolicyOrderState | undefined;
            resourceInputs["afterPredefinedIds"] = state?.afterPredefinedIds;
            resourceInputs["beforePredefinedIds"] = state?.beforePredefinedIds;
            resourceInputs["destinationZoneId"] = state?.destinationZoneId;
            resourceInputs["site"] = state?.site;
            resourceInputs["sourceZoneId"] = state?.sourceZoneId;
        } else {
            const args = argsOrState as ZonePolicyOrderArgs | undefined;
            if (args?.destinationZoneId === undefined && !opts.urn) {
                throw new Error("Missing required property 'destinationZoneId'");
            }
            if (args?.sourceZoneId === undefined && !opts.urn) {
                throw new Error("Missing required property 'sourceZoneId'");
            }
            resourceInputs["afterPredefinedIds"] = args?.afterPredefinedIds;
            resourceInputs["beforePredefinedIds"] = args?.beforePredefinedIds;
            resourceInputs["destinationZoneId"] = args?.destinationZoneId;
            resourceInputs["site"] = args?.site;
            resourceInputs["sourceZoneId"] = args?.sourceZoneId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ZonePolicyOrder.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ZonePolicyOrder resources.
 */
export interface ZonePolicyOrderState {
    /**
     * Ordered IDs of custom `unifi.firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
     */
    afterPredefinedIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Ordered IDs of custom `unifi.firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
     */
    beforePredefinedIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
     */
    destinationZoneId?: pulumi.Input<string>;
    /**
     * The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
     */
    site?: pulumi.Input<string>;
    /**
     * ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
     */
    sourceZoneId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ZonePolicyOrder resource.
 */
export interface ZonePolicyOrderArgs {
    /**
     * Ordered IDs of custom `unifi.firewall.ZonePolicy` policies that run AFTER the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
     */
    afterPredefinedIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Ordered IDs of custom `unifi.firewall.ZonePolicy` policies that run BEFORE the predefined (built-in) policies for this zone pair. Order within the list is significant. Omit this attribute when it is unused rather than setting it to an empty list (`[]`).
     */
    beforePredefinedIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * ID of the destination firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
     */
    destinationZoneId: pulumi.Input<string>;
    /**
     * The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
     */
    site?: pulumi.Input<string>;
    /**
     * ID of the source firewall zone of the pair whose policy order is managed. Changing the zone pair forces a new resource.
     */
    sourceZoneId: pulumi.Input<string>;
}
